### ISSUE TITLE
Cmd + Shift + : opens remnote help menu on the desktop MAC APP

### ISSUE THREAD

**Issue by Saadchr** [bjsi/cloze-hints#4]
Cmd + Shift + : opens remnote help menu on the desktop MAC APP

**Comment by bjsi** [comment]
Sorry about that! It is quite hard to find non-overlapping shortcuts :sweat_smile: In the next version, either 1.8.31 or 1.8.32 (getting deployed right now), you will be able to change plugin shortcuts in the keyboard shortcuts menu in the settings.

**Comment by bjsi** [comment]
@Saadchr You should be able to change the shortcut now :)
