### ISSUE TITLE
Hints often missing on flashcards and edit mode

### ISSUE THREAD

**Issue by TitanEsXVI** [bjsi/cloze-hints#6]
I have this problem with the plugin that when I create a hint for my cloze card, they don't appear while studying flashcards or in the editor
Here is: [Hint plugin video](https://drive.google.com/file/d/1WqHLuE3XbcJH0I0_ryFvjrSZLGYwFnXQ/view?usp=share_link)

**Comment by bjsi** [comment]
Sorry for the delay in getting back to you. I'm trying to work on a fix now +1

**Comment by bjsi** [comment]
Ok actually I think I fixed it. The issue happened when editing Rem containing cloze hints. If you deleted a cloze hint, then it would cause the error.
