### ISSUE TITLE
Does not always work

### ISSUE THREAD

**Issue by winniebean23** [bjsi/cloze-hints#7]
More often than not, the cloze hint doesn't even show up in my flashcards. This was such a good idea, and it worked for a short period of time, but all of a sudden its just stopped working properly.

**Comment by bjsi** [comment]
I'm struggling to reproduce the issue. Could you let me know which platform you are using? (Web, Desktop, Mobile)

**Comment by bjsi** [comment]
Ok actually I think I fixed it. The issue happened when editing Rem containing cloze hints. If you deleted a cloze hint, then it would cause the error.
